version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./Dockerfile"
    tty: true
    image: node
    container_name: node
    volumes:
      - .:/usr/src/app
    command: sh -c "cd app && yarn start"
    ports:
      - "3000:3000"
