version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./Dockerfile"
    tty: true
    image: node
    container_name: node
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/app/node_modules
    ports:
      - "3000:3000"
