version: '3'
services:
  node:
    build:
      context: .
      dockerfile: "./Dockerfile"
    tty: true
    image: node
    container_name: node
    volumes:
      - .:/workspace:cached
      - node_modules:/workspace/app/node_modules
    # command: sh -c "cd app && yarn run dev"
    ports:
      - "3000:3000"
volumes:
  node_modules:
